/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readium_EPubPackage */

#ifndef _Included_com_readium_EPubPackage
#define _Included_com_readium_EPubPackage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_readium_EPubPackage
 * Method:    initWithPackage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_EPubPackage_initWithPackage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubPackage
 * Method:    freePackage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_EPubPackage_freePackage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubPackage
 * Method:    getSpinItems
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_readium_EPubPackage_getSpinItems
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubPackage
 * Method:    getArchiveReader
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_readium_EPubPackage_getArchiveReader
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_readium_EPubPackage
 * Method:    getTableOfContents
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_readium_EPubPackage_getTableOfContents
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubPackage
 * Method:    getManifestItems
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_readium_EPubPackage_getManifestItems
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubPackage
 * Method:    getMetadata
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_readium_EPubPackage_getMetadata
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
