/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readium_Metadata */

#ifndef _Included_com_readium_Metadata
#define _Included_com_readium_Metadata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_readium_Metadata
 * Method:    initMetadata
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_Metadata_initMetadata
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
