/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readium_EPubJNI */

#ifndef _Included_com_readium_EPubJNI
#define _Included_com_readium_EPubJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_readium_EPubJNI
 * Method:    getKeyIV
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_readium_EPubJNI_getKeyIV
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_readium_EPubJNI
 * Method:    isPathEncrypted
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_readium_EPubJNI_isPathEncrypted
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_readium_EPubJNI
 * Method:    openBook
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_readium_EPubJNI_openBook
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_readium_EPubJNI
 * Method:    closeBook
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_EPubJNI_closeBook
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubJNI
 * Method:    getPackages
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_readium_EPubJNI_getPackages
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubJNI
 * Method:    staticInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_readium_EPubJNI_staticInitialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
