/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readium_ManifestItem */

#ifndef _Included_com_readium_ManifestItem
#define _Included_com_readium_ManifestItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_readium_ManifestItem
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_ManifestItem_init
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
