/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readium_EPubSpinelItem */

#ifndef _Included_com_readium_EPubSpinelItem
#define _Included_com_readium_EPubSpinelItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_readium_EPubSpinelItem
 * Method:    freeSpinelItem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_EPubSpinelItem_freeSpinelItem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_EPubSpinelItem
 * Method:    initSpinelItem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_EPubSpinelItem_initSpinelItem
  (JNIEnv *, jobject, jlong);

void setStringProperty(JNIEnv *env, jobject thiz, char* fieldName,
		char* value);

#ifdef __cplusplus
}
#endif
#endif
