/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readium_ResourceStream */

#ifndef _Included_com_readium_ResourceStream
#define _Included_com_readium_ResourceStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_readium_ResourceStream_MAX_SKIP_BUFFER_SIZE
#define com_readium_ResourceStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     com_readium_ResourceStream
 * Method:    readNative
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_readium_ResourceStream_readNative
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_readium_ResourceStream
 * Method:    bytesLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_readium_ResourceStream_bytesLeft
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_ResourceStream
 * Method:    freeResourceStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_ResourceStream_freeResourceStream
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
