/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readium_NavigationElement */

#ifndef _Included_com_readium_NavigationElement
#define _Included_com_readium_NavigationElement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_readium_NavigationElement
 * Method:    initNavigationElement
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_readium_NavigationElement_initNavigationElement
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_readium_NavigationElement
 * Method:    getChildren
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_readium_NavigationElement_getChildren
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
